<?php
require_once __DIR__ . '/../includes/auth.php';
require_customer();
$customerId = (int) current_user()['customer_id'];
$upcoming = all_rows("SELECT a.*, s.service_name, CONCAT(st.first_name, ' ', st.last_name) staff_name FROM appointments a JOIN services s ON s.service_id = a.service_id JOIN staff st ON st.staff_id = a.staff_id WHERE a.customer_id = ? AND a.status = 'Scheduled' AND a.appointment_date >= CURDATE() ORDER BY a.appointment_date, a.appointment_time LIMIT 5", [$customerId]);
$history = all_rows("SELECT a.*, s.service_name, CONCAT(st.first_name, ' ', st.last_name) staff_name FROM appointments a JOIN services s ON s.service_id = a.service_id JOIN staff st ON st.staff_id = a.staff_id WHERE a.customer_id = ? ORDER BY a.appointment_date DESC, a.appointment_time DESC LIMIT 5", [$customerId]);
$serviceCount = (int) scalar("SELECT COUNT(*) FROM services WHERE status = 'Active'");
$page_title = 'My Customer Portal'; $customer_active = 'home'; require __DIR__ . '/../includes/customer_header.php';
?>
<section class="customer-welcome"><div><div class="hero-kicker">WELCOME BACK</div><h2 class="hero-title">Ready for your next glow-up?</h2><p class="hero-copy">Choose your service, preferred stylist and time. We’ll take care of the rest.</p><a class="btn btn-light" href="<?= e(app_url('customer_portal/book.php')) ?>"><i class="bi bi-calendar-plus me-1"></i> Book a visit</a></div><div class="customer-welcome-art"><i class="bi bi-flower1"></i></div></section>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="customer-stat"><span class="customer-stat-icon blue"><i class="bi bi-calendar-heart"></i></span><div><strong><?= count($upcoming) ?></strong><small>Upcoming visits</small></div></div></div><div class="col-md-4"><div class="customer-stat"><span class="customer-stat-icon rose"><i class="bi bi-stars"></i></span><div><strong><?= $serviceCount ?></strong><small>Services available</small></div></div></div><div class="col-md-4"><div class="customer-stat"><span class="customer-stat-icon gold"><i class="bi bi-clock-history"></i></span><div><strong><?= scalar('SELECT COUNT(*) FROM appointments WHERE customer_id = ?', [$customerId]) ?></strong><small>Total visits</small></div></div></div></div>
<div class="row g-4"><div class="col-lg-7"><div class="card table-card"><div class="card-header bg-white d-flex justify-content-between align-items-center"><h2 class="h5 mb-0">Your upcoming appointments</h2><a href="<?= e(app_url('customer_portal/appointments.php')) ?>" class="small">View all</a></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Date & time</th><th>Service</th><th>Staff</th><th>Status</th></tr></thead><tbody><?php if (!$upcoming): ?><tr><td colspan="4" class="text-center text-secondary py-4">No upcoming visits yet.</td></tr><?php endif; ?><?php foreach ($upcoming as $appointment): ?><tr><td><?= e(date('d M Y', strtotime($appointment['appointment_date']))) ?><br><small class="text-secondary"><?= e(date('H:i', strtotime($appointment['appointment_time']))) ?></small></td><td><?= e($appointment['service_name']) ?><br><small><?= money($appointment['service_price']) ?></small></td><td><?= e($appointment['staff_name']) ?></td><td><?= status_badge($appointment['status']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-lg-5"><div class="card table-card"><div class="card-header bg-white"><h2 class="h5 mb-0">Recent visits</h2></div><div class="list-group list-group-flush"><?php if (!$history): ?><div class="list-group-item text-secondary">Your visit history will appear here.</div><?php endif; ?><?php foreach ($history as $appointment): ?><div class="list-group-item d-flex justify-content-between align-items-center"><div><strong><?= e($appointment['service_name']) ?></strong><br><small class="text-secondary"><?= e(date('d M Y', strtotime($appointment['appointment_date']))) ?></small></div><?= status_badge($appointment['status']) ?></div><?php endforeach; ?></div></div></div></div>
<?php require __DIR__ . '/../includes/customer_footer.php';
