<?php
require_once __DIR__ . '/../includes/auth.php';
require_login();
$active_menu='products';
$products=all_rows("SELECT product_id, product_name, quantity, reorder_level FROM products WHERE status='Active' ORDER BY product_name");
$appointments=all_rows("SELECT a.appointment_id, a.appointment_date, CONCAT(c.first_name,' ',c.last_name) customer_name, s.service_name FROM appointments a JOIN customers c ON c.customer_id=a.customer_id JOIN services s ON s.service_id=a.service_id WHERE a.status IN ('Scheduled','Completed') ORDER BY a.appointment_date DESC, a.appointment_time DESC");
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf_or_redirect('products/usage.php');$productId=post_id('product_id');$appointmentId=post_id('appointment_id');$quantity=posted('quantity_used');$usageDate=posted('usage_date');$errors=[];$product=$productId?one_row('SELECT * FROM products WHERE product_id=?',[$productId]):null;
    if(!$product)$errors[]='Please select a valid product.';if($appointmentId<1 || !scalar('SELECT COUNT(*) FROM appointments WHERE appointment_id=?',[$appointmentId]))$errors[]='Please select a valid appointment.';if(!ctype_digit($quantity)||(int)$quantity<1)$errors[]='Quantity used must be a whole number of at least 1.';if($product && (int)$quantity>(int)$product['quantity'])$errors[]='Cannot record more product usage than the available stock.';if(!is_valid_date($usageDate))$errors[]='Please enter a valid usage date.';
    $form=compact('productId','appointmentId','quantity','usageDate');if($errors){$_SESSION['usage_errors']=$errors;$_SESSION['usage_form']=$form;redirect('products/usage.php');}
    try{db()->beginTransaction();$locked=one_row('SELECT quantity FROM products WHERE product_id=? FOR UPDATE',[$productId]);if(!$locked || (int)$locked['quantity']<(int)$quantity)throw new RuntimeException('Insufficient stock.');$insert=db()->prepare('INSERT INTO product_usage (product_id,appointment_id,quantity_used,usage_date) VALUES (?,?,?,?)');$insert->execute([$productId,$appointmentId,(int)$quantity,$usageDate]);$update=db()->prepare('UPDATE products SET quantity=quantity-? WHERE product_id=?');$update->execute([(int)$quantity,$productId]);db()->commit();$remaining=(int)$locked['quantity']-(int)$quantity;$message='Product usage recorded and stock updated.';if($remaining<=(int)$product['reorder_level'])$message.=' Product stock is low.';set_flash($remaining<=(int)$product['reorder_level']?'warning':'success',$message);}catch(Throwable $exception){if(db()->inTransaction())db()->rollBack();$_SESSION['usage_errors']=['Unable to record usage. Verify the available stock and try again.'];$_SESSION['usage_form']=$form;redirect('products/usage.php');}redirect('products/index.php');
}
$form=$_SESSION['usage_form']??['productId'=>'','appointmentId'=>'','quantity'=>'','usageDate'=>date('Y-m-d')];unset($_SESSION['usage_form']);$errors=$_SESSION['usage_errors']??[];unset($_SESSION['usage_errors']);$page_title='Record Product Usage';require __DIR__.'/../includes/header.php';
?>
<div class="card form-card shadow-sm"><div class="card-body p-4"><p class="text-secondary">Recording product usage automatically deducts the used quantity from stock. It will not allow negative stock.</p><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $error):?><li><?=e($error)?></li><?php endforeach;?></ul></div><?php endif;?><form method="post"><?=csrf_input()?><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Product</label><select class="form-select" name="product_id" required><option value="">Choose product…</option><?php foreach($products as $product):?><option value="<?= (int)$product['product_id']?>" <?= (int)$form['productId']===(int)$product['product_id']?'selected':''?>><?=e($product['product_name'])?> — <?= (int)$product['quantity']?> available</option><?php endforeach;?></select></div><div class="col-md-6 mb-3"><label class="form-label">Appointment</label><select class="form-select" name="appointment_id" required><option value="">Choose appointment…</option><?php foreach($appointments as $appointment):?><option value="<?= (int)$appointment['appointment_id']?>" <?= (int)$form['appointmentId']===(int)$appointment['appointment_id']?'selected':''?>>#<?= (int)$appointment['appointment_id']?> · <?=e($appointment['customer_name'])?> · <?=e($appointment['service_name'])?></option><?php endforeach;?></select></div><div class="col-md-6 mb-3"><label class="form-label">Quantity used</label><input class="form-control" type="number" name="quantity_used" min="1" step="1" value="<?=e($form['quantity'])?>" required></div><div class="col-md-6 mb-3"><label class="form-label">Usage date</label><input class="form-control" type="date" name="usage_date" value="<?=e($form['usageDate'])?>" required></div></div><button class="btn btn-primary">Record usage</button> <a class="btn btn-outline-secondary" href="<?=e(app_url('products/index.php'))?>">Cancel</a></form></div></div>
<?php require __DIR__.'/../includes/footer.php';
